### ISSUE TITLE
DSM not tracking my fishing xp

### ISSUE THREAD

**Issue by zooterxd** [bowser0000/SkyblockMod#102]
no idea why this is. defaults on farming xp and won't change from farming xp even while fishing

**Comment by SPCOxion** [comment]
This is due to a change in how the game tells you how much skill experience you have. Quoting from [the patch notes](https://hypixel.net/threads/skyblock-0-11-5.4280793/): "Changed the skill notification in the action bar from (274,308/1,200,00) to (22.9%) format".

The new format will give 2 decimal places without trailing zeroes (e.g. 12.34%, but 12.30% becomes 12.3%, and 12.00% becomes 12%). Seems to round to the nearest hundredth of a percentage. A fix would not only require a change to how the number is parsed, but also a conversion from percentage to "actual" experience based on the player's current skill level. It also means that some information like experience per hour will be less precise, especially at higher skill levels, and I don't think there's any way around that.

**Comment by GodSaveTheDoge** [comment]
>and I don't think there's any way around that.

maybe api if skill api on (?)
